Models/TeacherCourseStudent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Models
{
    public class TeacherCourseStudent
    {
        [Key]
        public int TeacherCourseStudentId { get; set; }
        [Required]
        public string TeacherCourseStudentSection { get; set; }

        public int TeacherId { get; set; }
        public TeacherTable Teacher { get; set; }
        public int CourseId { get; set; }
        public CourseTable Course { get; set; }


        public int StudentId { get; set; }
        public StudentTable Student { get; set; }

    }
}

Controllers/TeacherCourseStudentController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagementSystem.Data;
using SchoolManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Controllers
{
    public class TeacherCourseStudentController : Controller
    {
        private readonly MyDbContext _db;

        public TeacherCourseStudentController(MyDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<TeacherCourseStudent> TeacherCourseStudentList = _db.TeacherCourseStudentTable;
            return View(TeacherCourseStudentList);
        }



        //get-create= notun course create korar jonne
        public IActionResult Create()
        {
            return View();
        }




        //post-create= create click korar por ta database a pathanor jonne
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TeacherCourseStudent obj)
        {
            var stuid = obj.StudentId;
            var teid = obj.TeacherId;
            var couid = obj.CourseId;
            var stuobj = _db.StudentTable.Find(stuid);
            var teobj = _db.TeacherTable.Find(teid);
            var couobj = _db.CourseTable.Find(couid);
            if (teobj == null || teid == 0)
            {
                ModelState.AddModelError(nameof(TeacherCourseStudent.TeacherId), "TeachetID not found in the Database");
                /*return View(obj);*/
                /* ViewBag.Error = "No such TeacherId exits";
                return RedirectToAction("Index");*/
            }
            if (stuobj == null || stuid == 0)
            {
                ModelState.AddModelError(nameof(TeacherCourseStudent.StudentId), "StudentID not found in the Database");
               /* return View(obj);*/
                /*  ViewBag.Error = "No such StudentId exits";
                  return RedirectToAction ("Index");*/
            }
            if (couobj == null || couid == 0)
            {
                ModelState.AddModelError(nameof(TeacherCourseStudent.CourseId), "CourseID not found in the Database");
                /*return View(obj);*/
                /*ViewBag.Error = "No such CourseId exits";
               return RedirectToAction("Index");*/
            }
            if (ModelState.IsValid)
            {
                _db.TeacherCourseStudentTable.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


/**/
        //get-edit= edit course korar jonne
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.TeacherCourseStudentTable.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }



        //post-edit= edit click korar por ta database a pathanor jonne
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TeacherCourseStudent obj)
        {
            var stuid = obj.StudentId;
            var teid = obj.TeacherId;
            var couid = obj.CourseId;
            var stuobj = _db.StudentTable.Find(stuid);
            var teobj = _db.TeacherTable.Find(teid);
            var couobj = _db.CourseTable.Find(couid);
            if (teobj == null || teid == 0)
            {
                ModelState.AddModelError(nameof(TeacherCourseStudent.TeacherId), "TeachetID not found in the Database");
                /*return View(obj);*/
                /* ViewBag.Error = "No such TeacherId exits";
                return RedirectToAction("Index");*/
            }
            if (stuobj == null || stuid == 0)
            {
                ModelState.AddModelError(nameof(TeacherCourseStudent.StudentId), "StudentID not found in the Database");
                /* return View(obj);*/
                /*  ViewBag.Error = "No such StudentId exits";
                  return RedirectToAction ("Index");*/
            }
            if (couobj == null || couid == 0)
            {
                ModelState.AddModelError(nameof(TeacherCourseStudent.CourseId), "CourseID not found in the Database");
                /*return View(obj);*/
                /*ViewBag.Error = "No such CourseId exits";
               return RedirectToAction("Index");*/
            }
            if (ModelState.IsValid)
            {
                _db.TeacherCourseStudentTable.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.TeacherCourseStudentTable.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.TeacherCourseStudentTable.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.TeacherCourseStudentTable.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/TeacherCourseStudent/Create.cshtml
@model SchoolManagementSystem.Models.TeacherCourseStudent

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Add TeacherCourseStudent Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                @*<div class="form-group row">
                        <div class="col-4">
                            <label asp-for="StudentId"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="StudentId" class="form-control" />
                            <span asp-validation-for="StudentId" class="text-danger"></span>
                        </div>

                    </div>*@
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherCourseStudentSection"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherCourseStudentSection" class="form-control" />
                        <span asp-validation-for="TeacherCourseStudentSection" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherId" class="form-control" />
                        <span asp-validation-for="TeacherId" class="text-danger"></span>
                      @*  @Html.ValidationMessageFor(m => m.TeacherId)*@
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentId" class="form-control" />
                        <span asp-validation-for="StudentId" class="text-danger"></span>
                     @*   @Html.ValidationMessageFor(m => m.StudentId)*@
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseId" class="form-control" />
                        <span asp-validation-for="CourseId" class="text-danger"></span>
                        @*@Html.ValidationMessageFor(m => m.CourseId)*@
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/TeacherCourseStudent/Delete.cshtml
@model SchoolManagementSystem.Models.TeacherCourseStudent

<form method="post" asp-controller="TeacherCourseStudent" asp-route-Id="@Model.TeacherCourseStudentId" asp-action="DeletePost">
    <input asp-for="TeacherCourseStudentId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete TeacherCourseStudent Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherCourseStudentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherCourseStudentId" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherCourseStudentSection"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherCourseStudentSection" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherId" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentId" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseId" disabled class="form-control" />
                    </div>

                </div>

                
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/TeacherCourseStudent/Edit.cshtml
@model SchoolManagementSystem.Models.TeacherCourseStudent

<form method="post" asp-controller="TeacherCourseStudent" asp-route-Id="@Model.TeacherCourseStudentId">
    <input asp-for="TeacherCourseStudentId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit TeacherCourseStudent Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherCourseStudentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherCourseStudentId" class="form-control" />
                        <span asp-validation-for="TeacherCourseStudentId" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherCourseStudentSection"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherCourseStudentSection" class="form-control" />
                        <span asp-validation-for="TeacherCourseStudentSection" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherId" class="form-control" />
                        <span asp-validation-for="TeacherId" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentId" class="form-control" />
                        <span asp-validation-for="StudentId" class="text-danger"></span>
                    </div>

                </div>


                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseId" class="form-control" />
                        <span asp-validation-for="CourseId" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/TeacherCourseStudent/Index.cshtml
@model IEnumerable<SchoolManagementSystem.Models.TeacherCourseStudent>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">TeacherCourseStudent List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="TeacherCourseStudent" asp-action="Create" class="btn btn-success">
                Add New TeacherCourseStudent
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        TeacherCourseStudentId
                    </th>
                    <th>
                        TeacherCourseStudentSection
                    </th>
                    <th>
                        TeacherId
                    </th>
                    <th>
                        StudentId
                    </th>
                    <th>
                        CourseId
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="15%">@obj.TeacherCourseStudentId</td>
                        <td width="15%">@obj.TeacherCourseStudentSection</td>
                        <td width="10%">@obj.TeacherId</td>
                        <td width="10%">@obj.StudentId</td>
                        <td width="10%">@obj.CourseId</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="TeacherCourseStudent" asp-route-Id="@obj.TeacherCourseStudentId" asp-action="Edit" class="btn btn-primary mx-1">
                                    Edit
                                </a>
                                <br />
                                <a asp-controller="TeacherCourseStudent" asp-route-Id="@obj.TeacherCourseStudentId" asp-action="Delete" class="btn btn-danger mx-1">
                                    Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No TeacherCourseStudent Exits</p>
    }
</div>