Models/TeacherTable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Models
{
    public class TeacherTable
    {
        [Key]
        public int TeacherId { get; set; }
        [Required]
        public string TeacherName { get; set; }
        [Required]
        [StringLength(11, ErrorMessage = "Phone number length can't be more than 11.")]
        public string TeacherPhone { get; set; }
        [Required]
        [EmailAddress]
        public string TeacherEmail { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Address length can't be more than 50.")]
        public string TeacherAddress { get; set; }
        [Required]
        [StringLength(10, ErrorMessage = "Gender length can't be more than 11.")]
        public string TeacherGender { get; set; }
        [Required]
        public DateTime TeacherDOB { get; set; }


        
        public IList<TeacherCourseStudent> TeacherCourseStudents { get; set; }
    }
}

Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagementSystem.Data;
using SchoolManagementSystem.GenericRepo;
using SchoolManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Controllers
{
    public class TeacherController : Controller
    {



        private readonly IUnitOfWork _uow;

        public TeacherController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public ActionResult Index()
        {
            var model = _uow.teacherrepo.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TeacherTable model)
        {
            if (ModelState.IsValid)
            {
                _uow.teacherrepo.Insert(model);
                _uow.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            TeacherTable model = _uow.teacherrepo.GetById(id);
            return View(model);
        }
        [HttpPost]

        public ActionResult Edit(TeacherTable model)
        {
            if (ModelState.IsValid)
            {
                _uow.teacherrepo.Update(model);
                _uow.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            TeacherTable model = _uow.teacherrepo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult DeletePost(int id)
        {
            _uow.teacherrepo.DeletePost(id);
            _uow.Save();
            return RedirectToAction("Index");
        }



        /* private IRepository<TeacherTable> repo = null;
         *//*private IRepository Repository { get; set; }*/

        /*public CourseController()
        {
            this.repo = new Repository<CourseTable>();
        }*//*

        public TeacherController(IRepository<TeacherTable> repo)
        {
            this.repo = repo;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = repo.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TeacherTable model)
        {
            if (ModelState.IsValid)
            {
                repo.Insert(model);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            TeacherTable model = repo.GetById(id);
            return View(model);
        }

        [HttpPost]

        public ActionResult Edit(TeacherTable model)
        {
            if (ModelState.IsValid)
            {
                repo.Update(model);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            TeacherTable model = repo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult DeletePost(int id)
        {
            repo.DeletePost(id);
            repo.Save();
            return RedirectToAction("Index");
        }

*/












        /*
                private readonly MyDbContext _db;

                public TeacherController(MyDbContext db)
                {
                    _db = db;
                }

                public IActionResult Index()
                {
                    IEnumerable<TeacherTable> TeacherList = _db.TeacherTable;
                    return View(TeacherList);
                }



                //get-create= notun course create korar jonne
                public IActionResult Create()
                {
                    return View();
                }




                //post-create= create click korar por ta database a pathanor jonne
                [HttpPost]
                [ValidateAntiForgeryToken]
                public IActionResult Create(TeacherTable teacher)
                {
                    if (ModelState.IsValid)
                    {
                        _db.TeacherTable.Add(teacher);
                        _db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(teacher);
                }



                //get-edit= edit course korar jonne
                public IActionResult Edit(int? id)
                {
                    if (id == null || id == 0)
                    {
                        return NotFound();
                    }
                    var obj = _db.TeacherTable.Find(id);
                    if (obj == null)
                    {
                        return NotFound();
                    }

                    return View(obj);
                }



                //post-edit= edit click korar por ta database a pathanor jonne
                [HttpPost]
                [ValidateAntiForgeryToken]
                public IActionResult Edit(TeacherTable teacher)
                {
                    if (ModelState.IsValid)
                    {
                        _db.TeacherTable.Update(teacher);
                        _db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(teacher);
                }


                //GET - DELETE
                public IActionResult Delete(int? id)
                {
                    if (id == null || id == 0)
                    {
                        return NotFound();
                    }
                    var obj = _db.TeacherTable.Find(id);
                    if (obj == null)
                    {
                        return NotFound();
                    }

                    return View(obj);
                }

                //POST - DELETE
                [HttpPost]
                public IActionResult DeletePost(int? id)
                {
                    var obj = _db.TeacherTable.Find(id);
                    if (obj == null)
                    {
                        return NotFound();
                    }
                    _db.TeacherTable.Remove(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }*/

    }
}

Views/Teacher/Create.cshtml
@model SchoolManagementSystem.Models.TeacherTable

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Teacher Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                @*<div class="form-group row">
            <div class="col-4">
                <label asp-for="StudentId"></label>
            </div>
            <div class="col-8">
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>

        </div>*@
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherName" class="form-control" />
                        <span asp-validation-for="TeacherName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherPhone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherPhone" class="form-control" />
                        <span asp-validation-for="TeacherPhone" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherEmail" class="form-control" />
                        <span asp-validation-for="TeacherEmail" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherAddress" class="form-control" />
                        <span asp-validation-for="TeacherAddress" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherGender"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherGender" class="form-control" />
                        <span asp-validation-for="TeacherGender" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherDOB"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherDOB" class="form-control" />
                        <span asp-validation-for="TeacherDOB" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Teacher/Delete.cshtml
@model SchoolManagementSystem.Models.TeacherTable

<form method="post" asp-controller="Teacher" asp-route-Id="@Model.TeacherId" asp-action="DeletePost">
    <input asp-for="TeacherId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Teacher Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherId" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherName" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherPhone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherPhone" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherEmail" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherAddress" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherGender"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherGender" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherDOB"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherDOB" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Teacher/Edit.cshtml
@model SchoolManagementSystem.Models.TeacherTable

<form method="post" asp-controller="Teacher" asp-route-Id="@Model.TeacherId">
    <input asp-for="TeacherId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Teacher Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherId" class="form-control" />
                        <span asp-validation-for="TeacherId" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherName" class="form-control" />
                        <span asp-validation-for="TeacherName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherPhone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherPhone" class="form-control" />
                        <span asp-validation-for="TeacherPhone" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherEmail" class="form-control" />
                        <span asp-validation-for="TeacherEmail" class="text-danger"></span>
                    </div>

                </div>


                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherAddress" class="form-control" />
                        <span asp-validation-for="TeacherAddress" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherGender"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherGender" class="form-control" />
                        <span asp-validation-for="TeacherGender" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TeacherDOB"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherDOB" class="form-control" />
                        <span asp-validation-for="TeacherDOB" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Teacher/Index.cshtml
@model IEnumerable<SchoolManagementSystem.Models.TeacherTable>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Teacher List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Teacher" asp-action="Create" class="btn btn-success">
                Add New Teacher
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        TeacherId
                    </th>
                    <th>
                        TeacherName
                    </th>
                    <th>
                        TeacherPhone
                    </th>
                    <th>
                        TeacherEmail
                    </th>
                    <th>
                        TeacherAddress
                    </th>
                    <th>
                        TeacherGender
                    </th>
                    <th>
                        TeacherDOB
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="5%">@obj.TeacherId</td>
                    <td width="10%">@obj.TeacherName</td>
                    <td width="10%">@obj.TeacherPhone</td>
                    <td width="15%">@obj.TeacherEmail</td>
                    <td width="15%">@obj.TeacherAddress</td>
                    <td width="5%">@obj.TeacherGender</td>
                    <td width="5%">@obj.TeacherDOB</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Teacher" asp-route-Id="@obj.TeacherId" asp-action="Edit" class="btn btn-primary mx-1">
                                Edit
                            </a>
                            <br />
                            <a asp-controller="Teacher" asp-route-Id="@obj.TeacherId" asp-action="Delete" class="btn btn-danger mx-1 mr-4">
                                Delete
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Teacher Exits</p>
    }
</div>