Models/StudentTable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Models
{
    public class StudentTable
    {
        [Key]
        public int StudentId { get; set; }
        [Required]
        public string StudentName { get; set; }
        [Required]
        [StringLength(11, ErrorMessage = "Phone number length can't be more than 11.")]
        public string StudentPhone { get; set; }
        [Required]
        [StringLength(10, ErrorMessage = "Gender length can't be more than 10.")]
        public string StudentGender { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Address length can't be more than 50.")]
        public string StudentAddress { get; set; }
       
        public IList<TeacherCourseStudent> TeacherCourseStudents { get; set; }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagementSystem.Data;
using SchoolManagementSystem.GenericRepo;
using SchoolManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Controllers
{
    public class StudentController : Controller
    {
        private readonly IUnitOfWork _uow;

        public StudentController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public ActionResult Index()
        {
            var model = _uow.studentrepo.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(StudentTable model)
        {
            if (ModelState.IsValid)
            {
                _uow.studentrepo.Insert(model);
                _uow.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            StudentTable model = _uow.studentrepo.GetById(id);
            return View(model);
        }
        [HttpPost]

        public ActionResult Edit(StudentTable model)
        {
            if (ModelState.IsValid)
            {
                _uow.studentrepo.Update(model);
                _uow.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            StudentTable model = _uow.studentrepo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult DeletePost(int id)
        {
            _uow.studentrepo.DeletePost(id);
            _uow.Save();
            return RedirectToAction("Index");
        }








        /*private IRepository<StudentTable> repo = null;

        public StudentController(IRepository<StudentTable> repoi)
        {
            this.repo = repoi;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = repo.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(StudentTable model)
        {
            if (ModelState.IsValid)
            {
                repo.Insert(model);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            StudentTable model = repo.GetById(id);
            return View(model);
        }

        [HttpPost]

        public ActionResult Edit(StudentTable model)
        {
            if (ModelState.IsValid)
            {
                repo.Update(model);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            StudentTable model = repo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult DeletePost(int id)
        {
            repo.DeletePost(id);
            repo.Save();
            return RedirectToAction("Index");
        }
*/































        /*private readonly MyDbContext _db;

        public StudentController(MyDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<StudentTable> StudentList = _db.StudentTable;
            return View(StudentList);
        }



        //get-create= notun course create korar jonne
        public IActionResult Create()
        {
            return View();
        }




        //post-create= create click korar por ta database a pathanor jonne
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudentTable student)
        {
            if (ModelState.IsValid)
            {
                _db.StudentTable.Add(student);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }



        //get-edit= edit course korar jonne
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.StudentTable.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }



        //post-edit= edit click korar por ta database a pathanor jonne
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StudentTable student)
        {
            if (ModelState.IsValid)
            {
                _db.StudentTable.Update(student);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }


        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.StudentTable.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.StudentTable.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.StudentTable.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }*/

    }
}

Views/Student/Create.cshtml
@model SchoolManagementSystem.Models.StudentTable

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Student</h2>
        </div>
        <div class="row">
            <div class="col-8">
                @*<div class="form-group row">
            <div class="col-4">
                <label asp-for="StudentId"></label>
            </div>
            <div class="col-8">
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>

        </div>*@
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentName" class="form-control" />
                        <span asp-validation-for="StudentName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentPhone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentPhone" class="form-control" />
                        <span asp-validation-for="StudentPhone" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentGender"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentGender" class="form-control" />
                        <span asp-validation-for="StudentGender" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentAddress" class="form-control" />
                        <span asp-validation-for="StudentAddress" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Student/Delete.cshtml
@model SchoolManagementSystem.Models.StudentTable

<form method="post" asp-controller="Student" asp-route-Id="@Model.StudentId" asp-action="DeletePost">
    <input asp-for="StudentId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Student Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentId" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentName" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentPhone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentPhone" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentGender"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentGender" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentAddress" disabled class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Student/Edit.cshtml
@model SchoolManagementSystem.Models.StudentTable

<form method="post" asp-controller="Student" asp-route-Id="@Model.StudentId">
    <input asp-for="StudentId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Student Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentId" class="form-control" />
                        <span asp-validation-for="StudentId" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentName" class="form-control" />
                        <span asp-validation-for="StudentName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentPhone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentPhone" class="form-control" />
                        <span asp-validation-for="StudentPhone" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentGender"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentGender" class="form-control" />
                        <span asp-validation-for="StudentGender" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="StudentAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StudentAddress" class="form-control" />
                        <span asp-validation-for="StudentAddress" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Student/Index.cshtml
@model IEnumerable<SchoolManagementSystem.Models.StudentTable>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Student List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Student" asp-action="Create" class="btn btn-success">
                Add New Student
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        StudentId
                    </th>
                    <th>
                        StudentName
                    </th>
                    <th>
                        StudentPhone
                    </th>
                    <th>
                        StudentGender
                    </th>
                    <th>
                        StudentAddress
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="10%">@obj.StudentId</td>
                    <td width="20%">@obj.StudentName</td>
                    <td width="20%">@obj.StudentPhone</td>
                    <td width="10%">@obj.StudentGender</td>
                    <td width="20%">@obj.StudentAddress</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Student" asp-route-Id="@obj.StudentId" asp-action="Edit" class="btn btn-primary mx-1">
                                Edit
                            </a>
                            <a asp-controller="Student" asp-route-Id="@obj.StudentId" asp-action="Delete" class="btn btn-danger mx-1">
                                Delete
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Student Exits</p>
    }
</div>