Models/CourseTable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Models
{
    public class CourseTable
    {
        [Key]
        public int CourseId { get; set; }
        [Required]
        public string CourseName { get; set; }
        [Required]
        [Range(1, 10, ErrorMessage = "CourseDuration must be greater than 0 and less than equal 10")]
        public int CourseDuration { get; set; }

        public IList<TeacherCourseStudent> TeacherCourseStudents { get; set; }

    }
}

Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagementSystem.Data;
using SchoolManagementSystem.GenericRepo;
using SchoolManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagementSystem.Controllers
{
    public class CourseController : Controller
    {

        private readonly IUnitOfWork _uow;

        public CourseController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public ActionResult Index()
        {
            var model = _uow.courserepo.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CourseTable model)
        {
            if (ModelState.IsValid)
            {
                _uow.courserepo.Insert(model);
                _uow.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            CourseTable model = _uow.courserepo.GetById(id);
            return View(model);
        }
        [HttpPost]

        public ActionResult Edit(CourseTable model)
        {
            if (ModelState.IsValid)
            {
                _uow.courserepo.Update(model);
                _uow.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            CourseTable model = _uow.courserepo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult DeletePost(int id)
        {
             _uow.courserepo.DeletePost(id);
            _uow.Save();
            return RedirectToAction("Index");
        }




















        /*
                private IRepository<CourseTable> repo = null;
                *//*private IRepository Repository { get; set; }*/

        /*public CourseController()
        {
            this.repo = new Repository<CourseTable>();
        }*//*

        public CourseController(IRepository<CourseTable>repo)
        {
            this.repo = repo; 
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = repo.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CourseTable model)
        {
            if(ModelState.IsValid)
            {
                repo.Insert(model);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

       
        public ActionResult Edit(int id)
        {
            CourseTable model = repo.GetById(id);
            return View(model);
        }
                [HttpPost]

        public ActionResult Edit(CourseTable model)
        {
            if (ModelState.IsValid)
            {
                repo.Update(model);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            CourseTable model = repo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult DeletePost(int id)
        {
            repo.DeletePost(id);
            repo.Save();
            return RedirectToAction("Index");
        }
*/













        /* private readonly MyDbContext _db;

         public CourseController(MyDbContext db)
         {
             _db = db;
         }

         public IActionResult Index()
         {
             IEnumerable<CourseTable> CourseList = _db.CourseTable;
             return View(CourseList);
         }



         //get-create= notun course create korar jonne
         public IActionResult Create()
         {
             return View();
         }




         //post-create= create click korar por ta database a pathanor jonne
         [HttpPost]
         [ValidateAntiForgeryToken]
         public IActionResult Create(CourseTable course)
         {
             if (ModelState.IsValid)
             {
                 _db.CourseTable.Add(course);
                 _db.SaveChanges();
                 return RedirectToAction("Index");
             }
             return View(course);
         }



         //get-edit= edit course korar jonne
         public IActionResult Edit(int? id)
         {
             if (id == null || id == 0)
             {
                 return NotFound();
             }
             var obj = _db.CourseTable.Find(id);
             if (obj == null)
             {
                 return NotFound();
             }

             return View(obj);
         }



         //post-edit= edit click korar por ta database a pathanor jonne
         [HttpPost]
         [ValidateAntiForgeryToken]
         public IActionResult Edit(CourseTable course)
         {
             if (ModelState.IsValid)
             {
                 _db.CourseTable.Update(course);
                 _db.SaveChanges();
                 return RedirectToAction("Index");
             }
             return View(course);
         }


         //GET - DELETE
         public IActionResult Delete(int? id)
         {
             if (id == null || id == 0)
             {
                 return NotFound();
             }
             var obj = _db.CourseTable.Find(id);
             if (obj == null)
             {
                 return NotFound();
             }

             return View(obj);
         }

         //POST - DELETE
         [HttpPost]
         public IActionResult DeletePost(int? id)
         {
             var obj = _db.CourseTable.Find(id);
             if (obj == null)
             {
                 return NotFound();
             }
             _db.CourseTable.Remove(obj);
             _db.SaveChanges();
             return RedirectToAction("Index");
         }
 */
    }
}

Views/Course/Create.cshtml
@model SchoolManagementSystem.Models.CourseTable

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Course</h2>
        </div>
        <div class="row">
            <div class="col-8">
                @*<div class="form-group row">
                        <div class="col-4">
                            <label asp-for="CourseId"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="CourseId" class="form-control" />
                            <span asp-validation-for="CourseId" class="text-danger"></span>
                        </div>

                    </div>*@
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseName" class="form-control" />
                        <span asp-validation-for="CourseName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseDuration"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseDuration" class="form-control" />
                        <span asp-validation-for="CourseDuration" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Course/Delete.cshtml
@model SchoolManagementSystem.Models.CourseTable

<form method="post" asp-controller="Course" asp-route-Id="@Model.CourseId" asp-action="DeletePost">
    <input asp-for="CourseId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Course</h2>
        </div>
        <div class="row">
            <div class="col-8">
                @*<div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseId" disabled class="form-control" />
                    </div>

                </div>*@
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseName" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseDuration"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseDuration" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Course/Edit.cshtml
@model SchoolManagementSystem.Models.CourseTable

<form method="post" asp-action="Edit" asp-controller="Course" asp-route-Id="@Model.CourseId" >
    <input asp-for="CourseId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Course</h2>
        </div>
        <div class="row">
            <div class="col-8">
               @* <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseId" class="form-control" />
                        <span asp-validation-for="CourseId" class="text-danger"></span>
                    </div>

                </div>*@
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseName" class="form-control" />
                        <span asp-validation-for="CourseName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CourseDuration"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CourseDuration" class="form-control" />
                        <span asp-validation-for="CourseDuration" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>


    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Course/Index.cshtml
@model IEnumerable<SchoolManagementSystem.Models.CourseTable>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Course List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Course" asp-action="Create" class="btn btn-success">
                 Create New Course
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        CourseId
                    </th>
                    <th>
                        CourseName
                    </th>
                    <th>
                        CourseDuration
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="20%">@obj.CourseId</td>
                    <td width="30%">@obj.CourseName</td>
                    <td width="20%">@obj.CourseDuration</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Course" asp-route-Id="@obj.CourseId" asp-action="Edit" class="btn btn-primary mx-2">Edit
                            </a>
                            <a asp-controller="Course" asp-route-Id="@obj.CourseId" asp-action="Delete" class="btn btn-danger mx-2">Delete
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
            </table>
    }
    else
    {
        <p>No Course Exits</p>
    }
    </div>